version: '3.8'

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: server
      MYSQL_USER: u1
      MYSQL_PASSWORD: p1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: